FROM python:3.10-slim

# システム依存パッケージ
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    cmake \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

# 必要なPythonパッケージ
COPY requirements.asobi.txt .
RUN pip install --upgrade pip
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r requirements.asobi.txt
RUN pip install 'git+https://github.com/facebookresearch/detectron2.git'

RUN apt-get update && apt-get install -y golang

# プロジェクトファイルをコピー
COPY . .

CMD ["/bin/bash"]